copy allwind.h allwind.hh
del allwind.h
rem C's **********************************
rem C's **********************************
rem C's **********************************
C-DOC -L3 -x0 -~z6 -s3 -z22 DLLSTACK.C
COPY $C-DOC$.NEW\DLLSTACK.C DLLWIND.C
rem CPP's **********************************
rem CPP's **********************************
rem CPP's **********************************
C-DOCDSK -L3 -x0 -~z6 -s3 -z22 MAINWIND.CPP
COPY $C-DOC$.NEW\MAINWIND.CPP MAINWIND.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 DDEWIND.CPP
COPY $C-DOC$.NEW\DDEWIND.CPP DDEWIND.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 DLLWIND.CPP
COPY $C-DOC$.NEW\DLLWIND.CPP DLLWIND.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 ASSEMBLY.CPP
COPY $C-DOC$.NEW\ ASSEMBLY.CPP ASSEMBLY.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 VECTOR.CPP
COPY $C-DOC$.NEW\VECTOR.CPP VECTOR.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 THREED.CPP
COPY $C-DOC$.NEW\THREED.CPP THREED.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 MYFILEWN.CPP
COPY $C-DOC$.NEW\MYFILEWN.CPP MYFILEWN.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 MYFILEED.CPP
COPY $C-DOC$.NEW\MYFILEED.CPP MYFILEED.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 NETWIND.CPP
COPY $C-DOC$.NEW\NETWIND.CPP NETWIND.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 GRAPHWIN.CPP
COPY $C-DOC$.NEW\GRAPHWIN.CPP GRAPHWIN.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 FILESWND.CPP
COPY $C-DOC$.NEW\FILESWND.CPP FILESWND.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 DLGWIND.CPP
COPY $C-DOC$.NEW\DLGWIND.CPP DLGWIND.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 EVAL.CPP
COPY $C-DOC$.NEW\EVAL.CPP EVAL.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 DIB.CPP
COPY $C-DOC$.NEW\DIB.CPP DIB.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 FILEWND.CPP
COPY $C-DOC$.NEW\FILEWND.CPP FILEWND.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 LIBLOC.CPP
COPY $C-DOC$.NEW\LIBLOC.CPP LIBLOC.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 UNIX.CPP
COPY $C-DOC$.NEW\UNIX.CPP UNIX.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 ERROR.CPP
COPY $C-DOC$.NEW\ERROR.CPP ERROR.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 IBMTERM.CPP
COPY $C-DOC$.NEW\IBMTERM.CPP IBMTERM.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 PAREN.CPP
COPY $C-DOC$.NEW\PAREN.CPP PAREN.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 TERM.CPP
COPY $C-DOC$.NEW\TERM.CPP TERM.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 MEM.CPP
COPY $C-DOC$.NEW\MEM.CPP MEM.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 WRKSP.CPP
COPY $C-DOC$.NEW\WRKSP.CPP WRKSP.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 INTERN.CPP
COPY $C-DOC$.NEW\INTERN.CPP INTERN.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 COMS.CPP
COPY $C-DOC$.NEW\COMS.CPP COMS.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 LOGODATA.CPP
COPY $C-DOC$.NEW\LOGODATA.CPP LOGODATA.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 LISTS.CPP
COPY $C-DOC$.NEW\LISTS.CPP LISTS.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 MAIN.CPP
COPY $C-DOC$.NEW\MAIN.CPP MAIN.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 COLORDLG.CPP
COPY $C-DOC$.NEW\COLORDLG.CPP COLORDLG.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 SIZEDLG.CPP
COPY $C-DOC$.NEW\SIZEDLG.CPP SIZEDLG.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 CMDWIND.CPP
COPY $C-DOC$.NEW\CMDWIND.CPP CMDWIND.CPP
C-DOC -L3 -x0 -~z6 -s3 -z16 INIT.CPP
COPY $C-DOC$.NEW\INIT.CPP INIT.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 MATH.CPP
COPY $C-DOC$.NEW\MATH.CPP MATH.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 FILES.CPP
COPY $C-DOC$.NEW\FILES.CPP FILES.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 GRAPHICS.CPP
COPY $C-DOC$.NEW\GRAPHICS.CPP GRAPHICS.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 PRINT.CPP
COPY $C-DOC$.NEW\PRINT.CPP PRINT.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 STATWIND.CPP
COPY $C-DOC$.NEW\STATWIND.CPP STATWIND.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 PARSE.CPP
COPY $C-DOC$.NEW\PARSE.CPP PARSE.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 AREAWIND.CPP
COPY $C-DOC$.NEW\AREAWIND.CPP AREAWIND.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 MMWIND.CPP
COPY $C-DOC$.NEW\MMWIND.CPP MMWIND.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 EDITWND.CPP
COPY $C-DOC$.NEW\EDITWND.CPP EDITWND.CPP
C-DOC -L3 -x0 -~z6 -s3 -z22 DEVWIND.CPP
COPY $C-DOC$.NEW\DEVWIND.CPP DEVWIND.CPP
rem H's **********************************
rem H's **********************************
rem H's **********************************
rem ******************************************
rem ********** C-DOC -L3 -x0 -~z6 -s3 -z22 EDITWND.H
rem ********** COPY $C-DOC$.NEW\EDITWND.H EDITWND.H
rem ******************************************
C-DOC -L3 -x0 -~z6 -s3 -z22 VECTOR.H
COPY $C-DOC$.NEW\VECTOR.H VECTOR.H
C-DOC -L3 -x0 -~z6 -s3 -z22 THREED.H
COPY $C-DOC$.NEW\THREED.H THREED.H
C-DOC -L3 -x0 -~z6 -s3 -z22 FILEWND.H
COPY $C-DOC$.NEW\FILEWND.H FILEWND.H
C-DOC -L3 -x0 -~z6 -s3 -z22 ALLWIND.H
COPY $C-DOC$.NEW\ALLWIND.H ALLWIND.H
C-DOC -L3 -x0 -~z6 -s3 -z22 GLOBALS.H
COPY $C-DOC$.NEW\GLOBALS.H GLOBALS.H
C-DOC -L3 -x0 -~z6 -s3 -z22 CLASS.H
COPY $C-DOC$.NEW\CLASS.H CLASS.H
C-DOC -L3 -x0 -~z6 -s3 -z22 IBMTERM.H
COPY $C-DOC$.NEW\IBMTERM.H IBMTERM.H
C-DOC -L3 -x0 -~z6 -s3 -z22 DIB.H
COPY $C-DOC$.NEW\DIB.H DIB.H
C-DOC -L3 -x0 -~z6 -s3 -z22 LOGO.H
COPY $C-DOC$.NEW\LOGO.H LOGO.H
C-DOC -L3 -x0 -~z6 -s3 -z22 FUNC.H
COPY $C-DOC$.NEW\FUNC.H FUNC.H
C-DOC -L3 -x0 -~z6 -s3 -z22 OWLRC.H
COPY $C-DOC$.NEW\OWLRC.H OWLRC.H
C-DOC -L3 -x0 -~z6 -s3 -z22 COLORDLG.H
COPY $C-DOC$.NEW\COLORDLG.H COLORDLG.H
C-DOC -L3 -x0 -~z6 -s3 -z22 LOGOX.H
COPY $C-DOC$.NEW\LOGOX.H LOGOX.H
C-DOC -L3 -x0 -~z6 -s3 -z22 LOGORC.H
COPY $C-DOC$.NEW\LOGORC.H LOGORC.H
C-DOC -L3 -x0 -~z6 -s3 -z22 CTL3D.H
COPY $C-DOC$.NEW\CTL3D.H CTL3D.H
copy allwind.hh allwind.h
