FMSLOGO_MAJOR_VERSION=6
FMSLOGO_MINOR_VERSION=34
FMSLOGO_MICRO_VERSION=0

FMSLOGO_VERSION_SUFFIX=

FMSLOGO_VERSION=$(FMSLOGO_MAJOR_VERSION).$(FMSLOGO_MINOR_VERSION).$(FMSLOGO_MICRO_VERSION)$(FMSLOGO_VERSION_SUFFIX)
