#
# Borland C++ IDE generated makefile
# Generated 10/15/2005 at 7:57:07 PM
#
.AUTODEPEND

!include ..\version.mk


#
# Borland C++ tools
#
IMPLIB  = Implib
BCC32   = Bcc32 +BccW32.cfg 
BCC32I  = Bcc32i +BccW32.cfg 
TLINK32 = TLink32
ILINK32 = Ilink32
TLIB    = TLib
BRC32   = Brc32
TASM32  = Tasm32
#
# IDE macros
#
#
# External tools
#
CompileHLP = hc31.exe  # IDE Command Line: $NOSWAP $CAP MSG(HC312MSG) $EDNAME


#
# Options
#
IDE_LinkFLAGS32 =  -LC:\BC5\LIB
IDE_ResFLAGS32 = 
LinkerLocalOptsAtW32_fmslogodexe =  -wdpl -went -wdup -wdef -wimt -wbdl -wsrf -wmsk -Tpe -aa -V4.0 -c -LC:\BC5\LIB
ResLocalOptsAtW32_fmslogodexe =  -l1033
BLocalOptsAtW32_fmslogodexe = 
CompInheritOptsAt_fmslogodexe = -IC:\BC5\INCLUDE -DSTRICT;_OWLPCH;
LinkerInheritOptsAt_fmslogodexe = -x
LinkerOptsAt_fmslogodexe = $(LinkerLocalOptsAtW32_fmslogodexe)
ResOptsAt_fmslogodexe = $(ResLocalOptsAtW32_fmslogodexe)
BOptsAt_fmslogodexe = $(BLocalOptsAtW32_fmslogodexe)
CompLocalOptsAtW16_helpblogodhlp = 
LinkerLocalOptsAtW16_helpblogodhlp = 
ResLocalOptsAtW16_helpblogodhlp = 
BLocalOptsAtW16_helpblogodhlp = 
CompOptsAt_helpblogodhlp = $(CompOptsAt_fmslogodexe) $(CompLocalOptsAtW16_helpblogodhlp)
CompInheritOptsAt_helpblogodhlp = -IC:\BC5\INCLUDE -DSTRICT;_OWLPCH;
LinkerInheritOptsAt_helpblogodhlp = -x
LinkerOptsAt_helpblogodhlp = $(LinkerOptsAt_fmslogodexe) $(LinkerLocalOptsAtW16_helpblogodhlp)
ResOptsAt_helpblogodhlp = $(ResOptsAt_fmslogodexe) $(ResLocalOptsAtW16_helpblogodhlp)
BOptsAt_helpblogodhlp = $(BOptsAt_fmslogodexe) $(BLocalOptsAtW16_helpblogodhlp)

#
# Dependency List
#
Dep_logo32 = \
   fmslogo.exe

logo32 : BccW32.cfg $(Dep_logo32)
  echo MakeNode

version.h : ..\version.mk
  generate-version.bat $(FMSLOGO_VERSION)

Dep_fmslogodexe = \
   logo.hlp\
   RELEASE\3dsolid.obj\
   RELEASE\assembly.obj\
   RELEASE\cmdwind.obj\
   RELEASE\colordlg.obj\
   RELEASE\commanderbutton.obj\
   RELEASE\coms.obj\
   RELEASE\devwind.obj\
   RELEASE\dib.obj\
   RELEASE\dlgwind.obj\
   RELEASE\dllstack.obj\
   RELEASE\dllwind.obj\
   RELEASE\editwnd.obj\
   RELEASE\areawind.obj\
   RELEASE\error.obj\
   RELEASE\eval.obj\
   RELEASE\files.obj\
   RELEASE\fileswnd.obj\
   RELEASE\filewnd.obj\
   RELEASE\gbm.obj\
   RELEASE\gbmhelp.obj\
   RELEASE\gbmgif.obj\
   RELEASE\gbmbmp.obj\
   RELEASE\gbmsize.obj\
   RELEASE\graphics.obj\
   RELEASE\graphwin.obj\
   RELEASE\ibmterm.obj\
   RELEASE\init.obj\
   RELEASE\intern.obj\
   RELEASE\libloc.obj\
   RELEASE\lists.obj\
   logo32.def\
   RELEASE\logodata.obj\
   RELEASE\logorc.res\
   RELEASE\main.obj\
   RELEASE\mainwind.obj\
   RELEASE\math.obj\
   RELEASE\mem.obj\
   RELEASE\mmwind.obj\
   RELEASE\myfileed.obj\
   RELEASE\myfilewn.obj\
   RELEASE\netwind.obj\
   RELEASE\paren.obj\
   RELEASE\parse.obj\
   RELEASE\print.obj\
   RELEASE\richedpr.obj\
   RELEASE\sizedlg.obj\
   RELEASE\statwind.obj\
   RELEASE\term.obj\
   RELEASE\threed.obj\
   RELEASE\utils.obj\
   RELEASE\unix.obj\
   RELEASE\vector.obj\
   RELEASE\wrksp.obj

fmslogo.exe : $(Dep_fmslogodexe)
  $(ILINK32) @&&|
 /v $(IDE_LinkFLAGS32) $(LinkerOptsAt_fmslogodexe) $(LinkerInheritOptsAt_fmslogodexe) +
C:\BC5\LIB\c0w32.obj+
RELEASE\3dsolid.obj+
RELEASE\assembly.obj+
RELEASE\cmdwind.obj+
RELEASE\colordlg.obj+
RELEASE\commanderbutton.obj+
RELEASE\coms.obj+
RELEASE\devwind.obj+
RELEASE\dib.obj+
RELEASE\dlgwind.obj+
RELEASE\dllstack.obj+
RELEASE\dllwind.obj+
RELEASE\editwnd.obj+
RELEASE\areawind.obj+
RELEASE\error.obj+
RELEASE\eval.obj+
RELEASE\files.obj+
RELEASE\fileswnd.obj+
RELEASE\filewnd.obj+
RELEASE\gbm.obj+
RELEASE\gbmhelp.obj+
RELEASE\gbmgif.obj+
RELEASE\gbmbmp.obj+
RELEASE\gbmsize.obj+
RELEASE\graphics.obj+
RELEASE\graphwin.obj+
RELEASE\ibmterm.obj+
RELEASE\init.obj+
RELEASE\intern.obj+
RELEASE\libloc.obj+
RELEASE\lists.obj+
RELEASE\logodata.obj+
RELEASE\main.obj+
RELEASE\mainwind.obj+
RELEASE\math.obj+
RELEASE\mem.obj+
RELEASE\mmwind.obj+
RELEASE\myfileed.obj+
RELEASE\myfilewn.obj+
RELEASE\netwind.obj+
RELEASE\paren.obj+
RELEASE\parse.obj+
RELEASE\print.obj+
RELEASE\richedpr.obj+
RELEASE\sizedlg.obj+
RELEASE\statwind.obj+
RELEASE\term.obj+
RELEASE\threed.obj+
RELEASE\utils.obj+
RELEASE\unix.obj+
RELEASE\vector.obj+
RELEASE\wrksp.obj
$<,$*
C:\BC5\LIB\owlwf.lib+
C:\BC5\LIB\bidsf.lib+
C:\BC5\LIB\ctl3d32.lib+
C:\BC5\LIB\import32.lib+
C:\BC5\LIB\cw32.lib
logo32.def
RELEASE\logorc.res

|
logo.hlp :  help\logo.hpj help\logo.rtf help\logo.cnt
  $(CompileHLP)   C:\logo-cvs\logo\src\help\logo.hpj

RELEASE\3dsolid.obj :  3dsolid.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ 3dsolid.cpp
|

RELEASE\assembly.obj :  assembly.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ assembly.cpp
|

RELEASE\cmdwind.obj :  cmdwind.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ cmdwind.cpp
|

RELEASE\colordlg.obj :  colordlg.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ colordlg.cpp
|

RELEASE\commanderbutton.obj :  commanderbutton.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ commanderbutton.cpp
|

RELEASE\coms.obj :  coms.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ coms.cpp
|

RELEASE\devwind.obj :  devwind.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ devwind.cpp
|

RELEASE\dib.obj :  dib.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ dib.cpp
|

RELEASE\dlgwind.obj :  dlgwind.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ dlgwind.cpp
|

RELEASE\dllstack.obj :  dllstack.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ dllstack.c
|

RELEASE\dllwind.obj :  dllwind.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ dllwind.cpp
|

RELEASE\editwnd.obj :  editwnd.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ editwnd.cpp
|

RELEASE\areawind.obj :  areawind.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ areawind.cpp
|

RELEASE\error.obj :  error.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ error.cpp
|

RELEASE\eval.obj :  eval.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ eval.cpp
|

RELEASE\files.obj :  files.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ files.cpp
|

RELEASE\fileswnd.obj :  fileswnd.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ fileswnd.cpp
|

RELEASE\filewnd.obj :  filewnd.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ filewnd.cpp
|

RELEASE\gbm.obj :  gbm.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ gbm.cpp
|

RELEASE\gbmhelp.obj :  gbmhelp.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ gbmhelp.cpp
|

RELEASE\gbmgif.obj :  gbmgif.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ gbmgif.cpp
|

RELEASE\gbmbmp.obj :  gbmbmp.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ gbmbmp.cpp
|

RELEASE\gbmsize.obj :  gbmsize.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ gbmsize.cpp
|

RELEASE\graphics.obj :  graphics.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ graphics.cpp
|

RELEASE\graphwin.obj :  graphwin.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ graphwin.cpp
|

RELEASE\ibmterm.obj :  ibmterm.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ ibmterm.cpp
|

RELEASE\init.obj :  init.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ init.cpp
|

RELEASE\intern.obj :  intern.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ intern.cpp
|

RELEASE\libloc.obj :  libloc.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ libloc.cpp
|

RELEASE\lists.obj :  lists.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ lists.cpp
|

RELEASE\logodata.obj :  logodata.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ logodata.cpp
|

RELEASE\logorc.res :  logorc.rc version.h
  $(BRC32) -R @&&|
 $(IDE_ResFLAGS32) $(ROptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe)  -FO$@ logorc.rc
|
RELEASE\printer.res :  ..\..\..\bc5\include\owl\printer.rc
  $(BRC32) -R @&&|
 $(IDE_ResFLAGS32) $(ROptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe)  -FO$@ ..\..\..\bc5\include\owl\printer.rc
|
RELEASE\inputdia.res :  ..\..\..\bc5\include\owl\inputdia.rc
  $(BRC32) -R @&&|
 $(IDE_ResFLAGS32) $(ROptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe)  -FO$@ ..\..\..\bc5\include\owl\inputdia.rc
|
RELEASE\picklist.res :  ..\..\..\bc5\include\owl\picklist.rc
  $(BRC32) -R @&&|
 $(IDE_ResFLAGS32) $(ROptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe)  -FO$@ ..\..\..\bc5\include\owl\picklist.rc
|
RELEASE\except.res :  ..\..\..\bc5\include\owl\except.rc
  $(BRC32) -R @&&|
 $(IDE_ResFLAGS32) $(ROptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe)  -FO$@ ..\..\..\bc5\include\owl\except.rc
|
RELEASE\stdwnds.res :  stdwnds.rc
  $(BRC32) -R @&&|
 $(IDE_ResFLAGS32) $(ROptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe)  -FO$@ stdwnds.rc
|
RELEASE\fileacc.res :  fileacc.rc
  $(BRC32) -R @&&|
 $(IDE_ResFLAGS32) $(ROptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe)  -FO$@ fileacc.rc
|
RELEASE\filemenu.res :  filemenu.rc
  $(BRC32) -R @&&|
 $(IDE_ResFLAGS32) $(ROptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe)  -FO$@ filemenu.rc
|
RELEASE\main.obj :  main.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ main.cpp
|

RELEASE\mainwind.obj :  mainwind.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ mainwind.cpp
|

RELEASE\math.obj :  math.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ math.cpp
|

RELEASE\mem.obj :  mem.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ mem.cpp
|

RELEASE\mmwind.obj :  mmwind.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ mmwind.cpp
|

RELEASE\myfileed.obj :  myfileed.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ myfileed.cpp
|

RELEASE\myfilewn.obj :  myfilewn.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ myfilewn.cpp
|

RELEASE\netwind.obj :  netwind.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ netwind.cpp
|

RELEASE\paren.obj :  paren.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ paren.cpp
|

RELEASE\parse.obj :  parse.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ parse.cpp
|

RELEASE\print.obj :  print.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ print.cpp
|

RELEASE\richedpr.obj :  richedpr.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ richedpr.cpp
|

RELEASE\sizedlg.obj :  sizedlg.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ sizedlg.cpp
|

RELEASE\statwind.obj :  statwind.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ statwind.cpp
|

RELEASE\term.obj :  term.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ term.cpp
|

RELEASE\threed.obj :  threed.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ threed.cpp
|

RELEASE\utils.obj :  utils.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ utils.cpp
|

RELEASE\unix.obj :  unix.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ unix.cpp
|

RELEASE\vector.obj :  vector.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ vector.cpp
|

RELEASE\wrksp.obj :  wrksp.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_fmslogodexe) $(CompInheritOptsAt_fmslogodexe) -o$@ wrksp.cpp
|

# Compiler configuration file
BccW32.cfg : 
   Copy &&|
-w
-R
-v
-WM-
-vi
-H
-H=logo32x.csm
-v-
-R-
-k-
-N
-H=LOGO.CSM
-Og
-Oi
-Ov
-Z
-O
-Oe
-Ol
-Ob
-OW
-O-a
-Om
-Op
-wbbf
-wpin
-wnak
-wdef
-wnod
-wamb
-wuse
-wstv
-wasm
-wamp
-wobs
-wpch
-w-pia
-waus
-wcln
-w-sig
-w-ucp
-O-d
-OS
-5
-W
-H"owl\pch.h"
-d
| $@


