nestit < ASSEMBLY.CPP > ASSEMBLY.NST
copy ASSEMBLY.NST ASSEMBLY.CPP
nestit < VECTOR.CPP > VECTOR.NST
copy VECTOR.NST VECTOR.CPP
nestit < THREED.CPP > THREED.NST
copy THREED.NST THREED.CPP
nestit < MYFILEWN.CPP > MYFILEWN.NST
copy MYFILEWN.NST MYFILEWN.CPP
nestit < MYFILEED.CPP > MYFILEED.NST
copy MYFILEED.NST MYFILEED.CPP
nestit < NETWIND.CPP > NETWIND.NST
copy NETWIND.NST NETWIND.CPP
nestit < GRAPHWIN.CPP > GRAPHWIN.NST
copy GRAPHWIN.NST GRAPHWIN.CPP
nestit < FILESWND.CPP > FILESWND.NST
copy FILESWND.NST FILESWND.CPP
nestit < DLGWIND.CPP > DLGWIND.NST
copy DLGWIND.NST DLGWIND.CPP
nestit < EVAL.CPP > EVAL.NST
copy EVAL.NST EVAL.CPP
nestit < DIB.CPP > DIB.NST
copy DIB.NST DIB.CPP
nestit < FILEWND.CPP > FILEWND.NST
copy FILEWND.NST FILEWND.CPP
nestit < LIBLOC.CPP > LIBLOC.NST
copy LIBLOC.NST LIBLOC.CPP
nestit < UNIX.CPP > UNIX.NST
copy UNIX.NST UNIX.CPP
nestit < ERROR.CPP > ERROR.NST
copy ERROR.NST ERROR.CPP
nestit < IBMTERM.CPP > IBMTERM.NST
copy IBMTERM.NST IBMTERM.CPP
nestit < PAREN.CPP > PAREN.NST
copy PAREN.NST PAREN.CPP
nestit < TERM.CPP > TERM.NST
copy TERM.NST TERM.CPP
nestit < MEM.CPP > MEM.NST
copy MEM.NST MEM.CPP
nestit < WRKSP.CPP > WRKSP.NST
copy WRKSP.NST WRKSP.CPP
nestit < INTERN.CPP > INTERN.NST
copy INTERN.NST INTERN.CPP
nestit < COMS.CPP > COMS.NST
copy COMS.NST COMS.CPP
nestit < LOGODATA.CPP > LOGODATA.NST
copy LOGODATA.NST LOGODATA.CPP
nestit < LISTS.CPP > LISTS.NST
copy LISTS.NST LISTS.CPP
nestit < MAIN.CPP > MAIN.NST
copy MAIN.NST MAIN.CPP
nestit < COLORDLG.CPP > COLORDLG.NST
copy COLORDLG.NST COLORDLG.CPP
nestit < SIZEDLG.CPP > SIZEDLG.NST
copy SIZEDLG.NST SIZEDLG.CPP
nestit < CMDWIND.CPP > CMDWIND.NST
copy CMDWIND.NST CMDWIND.CPP
nestit < INIT.CPP > INIT.NST
copy INIT.NST INIT.CPP
nestit < MATH.CPP > MATH.NST
copy MATH.NST MATH.CPP
nestit < FILES.CPP > FILES.NST
copy FILES.NST FILES.CPP
nestit < GRAPHICS.CPP > GRAPHICS.NST
copy GRAPHICS.NST GRAPHICS.CPP
nestit < PRINT.CPP > PRINT.NST
copy PRINT.NST PRINT.CPP
nestit < STATWIND.CPP > STATWIND.NST
copy STATWIND.NST STATWIND.CPP
nestit < PARSE.CPP > PARSE.NST
copy PARSE.NST PARSE.CPP
nestit < AREAWIND.CPP > AREAWIND.NST
copy AREAWIND.NST AREAWIND.CPP
nestit < MMWIND.CPP > MMWIND.NST
copy MMWIND.NST MMWIND.CPP
nestit < EDITWND.CPP > EDITWND.NST
copy EDITWND.NST EDITWND.CPP
nestit < MAINWIND.CPP > MAINWIND.NST
copy MAINWIND.NST MAINWIND.CPP
nestit < DEVWIND.CPP > DEVWIND.NST
copy DEVWIND.NST DEVWIND.CPP
rem H's **********************************
rem H's **********************************
rem H's **********************************
nestit < VECTOR.H > VECTOR.NST
copy VECTOR.NST VECTOR.H
nestit < THREED.H > THREED.NST
copy THREED.NST THREED.H
nestit < FILEWND.H > FILEWND.NST
copy FILEWND.NST FILEWND.H
nestit < ALLWIND.H > ALLWIND.NST
copy ALLWIND.NST ALLWIND.H
nestit < GLOBALS.H > GLOBALS.NST
copy GLOBALS.NST GLOBALS.H
nestit < CLASS.H > CLASS.NST
copy CLASS.NST CLASS.H
nestit < IBMTERM.H > IBMTERM.NST
copy IBMTERM.NST IBMTERM.H
nestit < DIB.H > DIB.NST
copy DIB.NST DIB.H
nestit < LOGO.H > LOGO.NST
copy LOGO.NST LOGO.H
nestit < FUNC.H > FUNC.NST
copy FUNC.NST FUNC.H
nestit < EDITWND.H > EDITWND.NST
copy EDITWND.NST EDITWND.H
nestit < OWLRC.H > OWLRC.NST
copy OWLRC.NST OWLRC.H
nestit < COLORDLG.H > COLORDLG.NST
copy COLORDLG.NST COLORDLG.H
nestit < LOGOX.H > LOGOX.NST
copy LOGOX.NST LOGOX.H
nestit < LOGORC.H > LOGORC.NST
copy LOGORC.NST LOGORC.H
nestit < CTL3D.H > CTL3D.NST
copy CTL3D.NST CTL3D.H
nestit < DDEWIND.CPP > DDEWIND.NST
copy DDEWIND.NST DDEWIND.CPP
nestit < DLLWIND.CPP > DLLWIND.NST
copy DLLWIND.NST DLLWIND.CPP
nestit < DLLSTACK.C > DLLSTACK.NST
copy DLLSTACK.NST DLLWIND.C

