/* Scintilla source code edit control */
/** @file SciLexer.h
 ** Interface to the added lexer functions in the SciLexer version of the edit control.
 **/
/* Copyright 1998-2002 by Neil Hodgson <neilh@scintilla.org>
 * The License.txt file describes the conditions under which this software may be distributed. */

/* Most of this file is automatically generated from the Scintilla.iface interface definition
 * file which contains any comments about the definitions. HFacer.py does the generation. */

#ifndef SCILEXER_H
#define SCILEXER_H

/* SciLexer features - not in standard Scintilla */

#define SCLEX_CONTAINER 0
#define SCLEX_NULL      1
#define SCLEX_FMSLOGO   2
#define SCLEX_AUTOMATIC 1000

#define SCE_FMS_DEFAULT          0
#define SCE_FMS_COMMENT          1
#define SCE_FMS_COMMENTBACKSLASH 2
#define SCE_FMS_STRING           3
#define SCE_FMS_STRING_VBAR      4

#define SCE_FMS_VBAR          5

#define SCE_FMS_VARIABLE      6
#define SCE_FMS_VARIABLE_VBAR 7

#define SCE_FMS_OPERATOR    8
#define SCE_FMS_NUMBER      9
#define SCE_FMS_IDENTIFIER  10

#define SCE_FMS_DEFAULT_BACKSLASH 11

#endif
